version: '3.7'
services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: app-nginx
    ports:
      - "80:80"
    depends_on:
      - "php"
    networks:
      - app_net
    volumes:
      - shared-volume:/var/www/html
    container_name: "compose-nginx"

  php:
    build: .
    image: app-php
    ports:
      - "9000:9000"
    depends_on:
      - "mysql"
    networks:
      - app_net
    volumes:
      - shared-volume:/var/www/html
    container_name: "compose-php"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app_net
    container_name: "compose-mysql"

networks:
  app_net:
    driver: bridge

volumes:
  shared-volume:
